# Generated by Django 5.0.6 on 2024-05-25 14:01

import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique account id')),
                ('email_id', models.EmailField(max_length=254, unique=True, verbose_name=' E-mail')),
                ('app_secret_token', models.CharField(default=secrets.token_urlsafe, max_length=50, unique=True, verbose_name='App secret token')),
                ('account_name', models.CharField(max_length=50, unique=True, verbose_name='Account name')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Account website url')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
